version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:16
    container_name: next-saas-pg
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: next-saas
    volumes:
      - next_saas_pg_data:/bitnami/postgresql

volumes:
  next_saas_pg_data:
