services:
  postgres:
    image: postgres:16
    container_name: next-saas-pg
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: next-saas
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - next_saas_pg_data:/var/lib/postgresql/data

volumes:
  next_saas_pg_data:
